pdf-service/data-config/summons-accused-qr.json
pdf-service/data-config/summons-accused.json
pdf-service/format-config/summons-accused-qr.json
pdf-service/format-config/summons-accused.json

rename summons.json in pdf-service and added additional template for pdf with qr code

---

pdf-service/data-config/witness-deposition.json

Reverts pucardotorg/kerala-configs#49

Revert "witnessdeposition object name change."

---

pdf-service/data-config/application-bail-bond-qr.json
pdf-service/data-config/application-case-transfer-qr.json
pdf-service/data-config/application-case-withdrawal-qr.json
pdf-service/data-config/application-production-of-documents-qr.json
pdf-service/data-config/order-for-accept-rescheduling-request-qr.json
pdf-service/data-config/order-for-accept-rescheduling-request.json
pdf-service/data-config/order-for-mandatory-async-submissions-and-response-qr.json
pdf-service/data-config/order-for-mandatory-async-submissions-and-response.json
pdf-service/data-config/order-for-rejection-rescheduling-request-qr.json
pdf-service/data-config/order-for-rejection-rescheduling-request.json
pdf-service/format-config/application-case-withdrawal.json
pdf-service/format-config/application-generic-qr.json
pdf-service/format-config/order-for-accept-rescheduling-request-qr.json
pdf-service/format-config/order-for-accept-rescheduling-request.json
pdf-service/format-config/order-for-mandatory-async-submissions-and-response-qr.json
pdf-service/format-config/order-for-mandatory-async-submissions-and-response.json
pdf-service/format-config/order-for-rejection-rescheduling-request-qr.json
pdf-service/format-config/order-for-rejection-rescheduling-request.json

order config added and fixed generics and rejection config

order config added and fixed generics and rejection config

---

pdf-service/data-config/order-202-crpc-qr.json
pdf-service/data-config/order-202-crpc.json
pdf-service/data-config/order-for-extension-deadline-qr.json
pdf-service/data-config/order-for-extension-deadline.json
pdf-service/data-config/order-reject-application-submission-deadline-qr.json
pdf-service/data-config/order-reject-application-submission-deadline.json
pdf-service/format-config/order-202-crpc-qr.json
pdf-service/format-config/order-202-crpc.json
pdf-service/format-config/order-for-extension-deadline-qr.json
pdf-service/format-config/order-for-extension-deadline.json
pdf-service/format-config/order-reject-application-submission-deadline-qr.json
pdf-service/format-config/order-reject-application-submission-deadline.json

PDF Config Creation of Order Under Section 202 CrPC, Order for Extension for Submission Deadline, Order for Rejection of Application for Submission Deadline

pdfCreationForOrders

---

pdf-service/data-config/mandatory-async-submissions-responses-qr.json
pdf-service/data-config/mandatory-async-submissions-responses.json
pdf-service/data-config/order-202-crpc-qr.json
pdf-service/data-config/order-202-crpc.json
pdf-service/data-config/order-for-mandatory-async-submissions-and-response-qr.json
pdf-service/data-config/order-for-mandatory-async-submissions-and-response.json
pdf-service/format-config/application-bail-bond-qr.json
pdf-service/format-config/application-bail-bond.json
pdf-service/format-config/mandatory-async-submissions-responses-qr.json
pdf-service/format-config/mandatory-async-submissions-responses.json
pdf-service/format-config/order-202-crpc-qr.json
pdf-service/format-config/order-202-crpc.json
pdf-service/format-config/order-for-mandatory-async-submissions-and-response-qr.json
pdf-service/format-config/order-for-mandatory-async-submissions-and-response.json

Styling related chnages in PDFs and some Variable Correction

Styling Changes

---

pdf-service/format-config/order-accept-voluntary-qr.json
pdf-service/format-config/order-reject-voluntary-qr.json

Key name fix for order-accept-voluntary-qr

key name fix

---

pdf-service/format-config/application-production-of-documents-qr.json
pdf-service/format-config/application-production-of-documents.json
pdf-service/format-config/order-bail-acceptance-qr.json
pdf-service/format-config/order-bail-acceptance.json
pdf-service/format-config/order-bail-rejection-qr.json
pdf-service/format-config/order-bail-rejection.json
pdf-service/format-config/order-for-extension-deadline-qr.json
pdf-service/format-config/order-for-extension-deadline.json

Template correction for bail Acceptance order

orderBailAcceptTemplateCorrection

---

pdf-service/format-config/order-notice-qr.json
pdf-service/format-config/order-notice.json

Notice Template Styling Issue Fix

---

pdf-service/data-config/warrants-non-bailable.json

[pucardtorg#2019](https://github.com/pucardotorg/dristi/issues/2019)

 warrant non-bailable pdf fixes.

---

pdf-service/data-config/summons-accused-qr.json
pdf-service/data-config/summons-accused.json
pdf-service/data-config/summons-witness-qr.json
pdf-service/data-config/summons-witness.json
pdf-service/data-config/warrants-bailable.json
pdf-service/data-config/warrants-non-bailable.json
pdf-service/format-config/summons-accused-qr.json
pdf-service/format-config/summons-accused.json
pdf-service/format-config/summons-witness-qr.json
pdf-service/format-config/summons-witness.json
pdf-service/format-config/warrants-bailable.json
pdf-service/format-config/warrants-non-bailable.json

[pucardtorg#2164](https://github.com/pucardotorg/dristi/issues/2164)

added courtCaseNumber as value for Summary trial.

---

pdf-service/format-config/notice-qr.json
pdf-service/format-config/notice.json
pdf-service/format-config/summons-accused-qr.json
pdf-service/format-config/summons-accused.json

[pucardtorg#2302](https://github.com/pucardotorg/dristi/issues/2302)

summons-notice pdf fixes.

---

pdf-service/data-config/complainant-case-efiling.json
pdf-service/format-config/complainant-case-efiling.json

https://github.com/pucardotorg/dristi/issues/1982 https://github.com/pucardotorg/dristi/issues/2276

added data and format json for complainant case pdf

---

pdf-service/data-config/schedule-hearing-date-qr.json
pdf-service/data-config/schedule-hearing-date.json
pdf-service/format-config/schedule-hearing-date-qr.json
pdf-service/format-config/schedule-hearing-date.json

Changes for https://github.com/pucardotorg/dristi/issues/1987

Template to include Purpose of Hearing

---

pdf-service/data-config/complainant-case-efiling.json
pdf-service/data-config/cover-page-pdf.json
pdf-service/data-config/docket-page.json
pdf-service/data-config/table-of-contents.json
pdf-service/format-config/complainant-case-efiling.json
pdf-service/format-config/cover-page-pdf.json
pdf-service/format-config/docket-page.json
pdf-service/format-config/table-of-contents.json

https://github.com/pucardotorg/dristi/issues/2368

cover-page, tables and complaint template

---

pdf-service/format-config/table-of-contents.json

https://github.com/pucardotorg/dristi/issues/2368

table of content jsonString change

---

pdf-service/data-config/complainant-case-efiling.json
pdf-service/data-config/table-of-contents.json
pdf-service/format-config/complainant-case-efiling.json
pdf-service/format-config/table-of-contents.json

https://github.com/pucardotorg/dristi/issues/2368

final changes for complaint and content pdf

---

egov-indexer/hearing-booking-indexer.yml

issue - https://github.com/pucardotorg/dristi/issues/1717

Bugs 1717 - added indexer yml for schedule hearing topics

---

pdf-service/data-config/complainant-case-efiling.json
pdf-service/format-config/complainant-case-efiling.json

https://github.com/pucardotorg/dristi/issues/1982

added filingNumber, changed header

---

pdf-service/data-config/order-issue-warrant-qr.json
pdf-service/data-config/order-issue-warrant.json
pdf-service/data-config/order-notice-qr.json
pdf-service/data-config/order-notice.json
pdf-service/data-config/schedule-hearing-date-qr.json
pdf-service/data-config/schedule-hearing-date.json
pdf-service/data-config/summons-issue-qr.json
pdf-service/data-config/summons-issue.json
pdf-service/format-config/order-issue-warrant-qr.json
pdf-service/format-config/order-issue-warrant.json
pdf-service/format-config/order-notice-qr.json
pdf-service/format-config/order-notice.json
pdf-service/format-config/schedule-hearing-date-qr.json
pdf-service/format-config/schedule-hearing-date.json
pdf-service/format-config/summons-issue-qr.json
pdf-service/format-config/summons-issue.json

https://github.com/pucardotorg/dristi/issues/2540

changed heading and designations of orders

---

pdf-service/data-config/notice.json
pdf-service/format-config/notice.json

change in notice pdf template

---

pdf-service/format-config/causeListPdf.json

change in court name

---

egov-persister/case-persister.yml
pdf-service/data-config/notice.json
pdf-service/format-config/causeListPdf.json
pdf-service/format-config/notice.json

* change in pdf alignment
* updated case persiter for edit case topic
* change in court name
* updated notice pdf format to have filing number (#222)
* updated notice pdf format to have filing number
* updated notice pdf format to have filing number
---------

Hot fix/1.0 (#223)

---

pdf-service/format-config/docket-page.json

Court Name Config Chnage

---

pdf-service/data-config/application-bail-bond-qr.json
pdf-service/data-config/application-bail-bond.json
pdf-service/data-config/application-delay-condonation-qr.json
pdf-service/data-config/application-delay-condonation.json
pdf-service/data-config/application-submit-bail-documents-qr.json
pdf-service/data-config/application-submit-bail-documents.json
pdf-service/data-config/order-acceptance-rejection-case-qr.json
pdf-service/data-config/order-acceptance-rejection-case.json
pdf-service/data-config/order-set-terms-of-bail-qr.json
pdf-service/data-config/order-set-terms-of-bail.json
pdf-service/format-config/application-bail-bond-qr.json
pdf-service/format-config/application-bail-bond.json
pdf-service/format-config/application-submit-bail-documents-qr.json
pdf-service/format-config/application-submit-bail-documents.json
pdf-service/format-config/order-acceptance-rejection-case-qr.json
pdf-service/format-config/order-acceptance-rejection-case.json
pdf-service/format-config/order-set-terms-of-bail-qr.json
pdf-service/format-config/order-set-terms-of-bail.json

https://github.com/pucardotorg/dristi/issues/2732
https://github.com/pucardotorg/dristi/issues/2737

updated some keys for configs for dca and bail

---

pdf-service/data-config/application-bail-bond-qr.json
pdf-service/data-config/application-bail-bond.json
pdf-service/data-config/application-submit-bail-documents-qr.json
pdf-service/data-config/application-submit-bail-documents.json
pdf-service/data-config/order-acceptance-rejection-case-qr.json
pdf-service/data-config/order-acceptance-rejection-case.json
pdf-service/data-config/order-bail-acceptance-qr.json
pdf-service/data-config/order-bail-acceptance.json
pdf-service/data-config/order-bail-rejection-qr.json
pdf-service/data-config/order-bail-rejection.json
pdf-service/data-config/order-set-terms-of-bail-qr.json
pdf-service/data-config/order-set-terms-of-bail.json

https://github.com/pucardotorg/dristi/issues/2732
https://github.com/pucardotorg/dristi/issues/2737

showing list bug fix in pdfs (removed .*)

---

pdf-service/format-config/order-acceptance-rejection-case.json

https://github.com/pucardotorg/dristi/issues/2747

updated case admit dismiss pdf format

---

pdf-service/data-config/bnss-notice-qr.json
pdf-service/data-config/bnss-notice.json
pdf-service/data-config/dca-notice-qr.json
pdf-service/data-config/dca-notice.json
pdf-service/format-config/bnss-notice-qr.json
pdf-service/format-config/bnss-notice.json
pdf-service/format-config/dca-notice-qr.json
pdf-service/format-config/dca-notice.json

BNSS and DCA Notice Templates (Feature 2760)

---

pdf-service/data-config/application-delay-condonation-qr.json
pdf-service/data-config/application-delay-condonation.json

https://github.com/pucardotorg/dristi-solutions/pull/1495

adding partyType to DCA Application

---

pdf-service/data-config/complainant-case-efiling.json
pdf-service/format-config/complainant-case-efiling.json

https://github.com/pucardotorg/dristi/issues/2881

updated complaint pdf for multiple litigants and advoactes

---

pdf-service/format-config/complainant-case-efiling.json

https://github.com/pucardotorg/dristi/issues/2881

Feature 2881: change for complaint pdf signatures and adding label

---

pdf-service/data-config/causeListPdf.json

[#2898](https://github.com/pucardotorg/dristi/issues/2898)

updated the way of iterating list

---

egov-persister/audit-service-persister.yml
egov-persister/case-diary-persister.yml

[#2869](https://github.com/pucardotorg/dristi/issues/2869)

added persister for diary entry

---

pdf-service/format-config/bnss-notice-qr.json
pdf-service/format-config/bnss-notice.json
pdf-service/format-config/notice-qr.json
pdf-service/format-config/notice.json

[#2592](https://github.com/pucardotorg/dristi/issues/2592)

Fix overlapping text

---

pdf-service/data-config/aDiary.json
pdf-service/format-config/aDiary.json

https://github.com/pucardotorg/dristi/issues/3095

added footer for a-diary

---

pdf-service/format-config/application-bail-bond-qr.json
pdf-service/format-config/application-bail-bond.json
pdf-service/format-config/application-case-transfer-qr.json
pdf-service/format-config/application-case-transfer.json
pdf-service/format-config/application-case-withdrawal-qr.json
pdf-service/format-config/application-case-withdrawal.json
pdf-service/format-config/application-delay-condonation-qr.json
pdf-service/format-config/application-delay-condonation.json
pdf-service/format-config/application-for-checkout-request-qr.json
pdf-service/format-config/application-for-checkout-request.json
pdf-service/format-config/application-generic-qr.json
pdf-service/format-config/application-generic.json
pdf-service/format-config/application-production-of-documents-qr.json
pdf-service/format-config/application-production-of-documents.json
pdf-service/format-config/application-reschedule-request-qr.json
pdf-service/format-config/application-reschedule-request.json
pdf-service/format-config/application-submission-extension-qr.json
pdf-service/format-config/application-submission-extension.json
pdf-service/format-config/application-submit-bail-documents-qr.json
pdf-service/format-config/application-submit-bail-documents.json

https://github.com/pucardotorg/dristi/issues/2922

All application template suggested chnages

---

pdf-service/data-config/order-bulk-reschedule-qr.json
pdf-service/data-config/order-bulk-reschedule.json
pdf-service/format-config/order-bulk-reschedule-qr.json
pdf-service/format-config/order-bulk-reschedule.json

https://github.com/pucardotorg/dristi/issues/3114

new config creation for bulk reschedule

---

pdf-service/data-config/order-admit-case-qr.json
pdf-service/data-config/order-admit-case.json
pdf-service/data-config/order-dismiss-case-qr.json
pdf-service/data-config/order-dismiss-case.json
pdf-service/format-config/order-admit-case-qr.json
pdf-service/format-config/order-admit-case.json
pdf-service/format-config/order-dismiss-case-qr.json
pdf-service/format-config/order-dismiss-case.json

[#3231](https://github.com/pucardotorg/dristi/issues/3231)

adding different admit and dismiss case configs

---

egov-persister/epost-tracker-persister.yml

https://github.com/pucardotorg/dristi/issues/3308

added postal hub's in persister file

---

pdf-service/data-config/summons-accused.json
pdf-service/format-config/summons-accused.json

https://github.com/pucardotorg/dristi/issues/3159

Change in summon Template as per change in summon Template

---

pdf-service/data-config/summons-accused.json
pdf-service/format-config/summons-accused.json

https://github.com/pucardotorg/dristi/issues/3490

Added Filing Number in Accused Summons

---

pdf-service/data-config/order-approval-rejection-litigant-details-qr.json
pdf-service/data-config/order-approval-rejection-litigant-details.json
pdf-service/format-config/order-approval-rejection-litigant-details-qr.json
pdf-service/format-config/order-approval-rejection-litigant-details.json

[#3425](https://github.com/pucardotorg/dristi/issues/3425)

adding pdf of order for approval/rejection of litigant details change

---

pdf-service/data-config/order-replace-advocate-qr.json
pdf-service/data-config/order-replace-advocate.json
pdf-service/format-config/order-replace-advocate-qr.json
pdf-service/format-config/order-replace-advocate.json

[#3423](https://github.com/pucardotorg/dristi/issues/3423)

[feature-3423] - formate and data config for replace advocate pdf template

---

pdf-service/data-config/complainant-case-efiling.json
pdf-service/format-config/complainant-case-efiling.json

https://github.com/pucardotorg/dristi/issues/3650

adding placeholder list in case pdf

---

pdf-service/format-config/complainant-case-efiling.json

[#3731](https://github.com/pucardotorg/dristi/issues/3731)

adv placeholder margin fix for poa feature

---

pdf-service/data-config/complainant-case-efiling.json
pdf-service/format-config/complainant-case-efiling.json

This reverts commit 7ef4e1b226c87a49b4b375ae88914e8d7a1277f5, reversing changes made to 69d1fc92aed0cee5f4801b44886c2135e8d467f0.

Revert "Merge pull request #349 from pucardotorg/develop-without-poa"

---

pdf-service/format-config/application-bail-bond-qr.json
pdf-service/format-config/application-bail-bond.json
pdf-service/format-config/application-generic-qr.json
pdf-service/format-config/application-generic.json
pdf-service/format-config/order-bulk-reschedule-qr.json
pdf-service/format-config/order-bulk-reschedule.json

https://github.com/pucardotorg/dristi/issues/3751

fix new changes for bulk reschedule pdf

---

pdf-service/data-config/schedule-hearing-date-qr.json
pdf-service/data-config/schedule-hearing-date.json
pdf-service/format-config/schedule-hearing-date-qr.json
pdf-service/format-config/schedule-hearing-date.json

add hearing summary section to schedule next hearing date templates #3990

schedule next hearing date templates change

---

pdf-service/data-config/schedule-hearing-date-qr.json
pdf-service/data-config/schedule-hearing-date.json
pdf-service/format-config/schedule-hearing-date-qr.json
pdf-service/format-config/schedule-hearing-date.json

add hearing summary section to schedule next hearing date templates
#3990

add hearing summary section to schedule next hearing date templates

---

pdf-service/data-config/docket-page.json
pdf-service/format-config/docket-page.json

https://github.com/pucardotorg/dristi/issues/3991

added document path in docket page

---

pdf-service/data-config/order-issue-warrant-qr.json
pdf-service/data-config/order-issue-warrant.json
pdf-service/format-config/order-issue-warrant-qr.json
pdf-service/format-config/order-issue-warrant.json

https://github.com/pucardotorg/dristi/issues/3852

Change in warrant template

---

pdf-service/data-config/bail-bond-qr.json
pdf-service/data-config/bail-bond.json
pdf-service/format-config/bail-bond-qr.json
pdf-service/format-config/bail-bond.json

https://github.com/pucardotorg/dristi/issues/4272

creation of bail bond pdf config

---

pdf-service/data-config/application-witness-deposition-qr.json
pdf-service/data-config/application-witness-deposition.json
pdf-service/format-config/application-witness-deposition-qr.json
pdf-service/format-config/application-witness-deposition.json

https://github.com/pucardotorg/dristi/issues/4409

added application deposition

---

pdf-service/data-config/order-issue-proclamation-qr.json
pdf-service/data-config/order-issue-proclamation.json
pdf-service/data-config/proclamation-generic.json
pdf-service/format-config/order-issue-proclamation-qr.json
pdf-service/format-config/order-issue-proclamation.json
pdf-service/format-config/proclamation-generic.json

[#4334](https://github.com/pucardotorg/dristi/issues/4334)

84-85 Orders and Task addition

---

pdf-service/data-config/new-order-generic.json
pdf-service/format-config/new-order-generic.json

https://github.com/pucardotorg/dristi/issues/4457

new order template

---

pdf-service/data-config/new-order-generic.json
pdf-service/format-config/new-order-generic.json

https://github.com/pucardotorg/dristi/issues/4613

added changes for new order template
